package edu.upenn.cis.citation.Corecover;

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Sep 12 10:07:39 VET 2006
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int imp = 7;
  public static final int coma = 8;
  public static final int cparen = 6;
  public static final int nomb = 4;
  public static final int EOF = 0;
  public static final int ctte = 3;
  public static final int error = 1;
  public static final int oparen = 5;
  public static final int var = 2;
}

